### ISSUE TITLE
pas.plugins.ldap fails with node.ext.ldap 0.9.7

### ISSUE THREAD

**Issue by saily** [bluedynamics/node.ext.ldap#9]
2015-02-17 14:44:11 ERROR pas.plugins.ldap Non-LDAP error while connection test!
    Traceback (most recent call last):
      File "/Users/daniel/Workspace/buildout.tr-eshop/src/pas.plugins.ldap/src/pas/plugins/ldap/properties.py", line 160, in connection_test
        ugm.users
      File "/Users/daniel/Workspace/buildout.tr-eshop/src/node.ext.ldap/src/node/ext/ldap/ugm/_api.py", line 1012, in users
        return self['users']
      File "/Users/daniel/Workspace/.buildout/eggs/plumber-1.3-py2.7.egg/plumber/_instructions.py", line 385, in entrance
        return plumbing_method(_next, self, *args, **kw)
      File "/Users/daniel/Workspace/.buildout/eggs/node-0.9.15-py2.7.egg/node/behaviors/nodespace.py", line 39, in __getitem__
        return _next(self, key)
      File "/Users/daniel/Workspace/.buildout/eggs/node-0.9.15-py2.7.egg/node/locking.py", line 31, in _locktree_decorator
        result = fn(self, *args, **kwargs)
      File "/Users/daniel/Workspace/buildout.tr-eshop/src/node.ext.ldap/src/node/ext/ldap/ugm/_api.py", line 980, in __getitem__
        self['users'] = Users(self.props, self.ucfg)
      File "/Users/daniel/Workspace/buildout.tr-eshop/src/node.ext.ldap/src/node/ext/ldap/ugm/_api.py", line 417, in __init__
        context = LDAPNode(name=cfg.baseDN, props=props)
      File "/Users/daniel/Workspace/.buildout/eggs/plumber-1.3-py2.7.egg/plumber/_instructions.py", line 385, in entrance
        return plumbing_method(_next, self, *args, **kw)
      File "/Users/daniel/Workspace/.buildout/eggs/node-0.9.15-py2.7.egg/node/behaviors/lifecycle.py", line 36, in __init__
        _next(self, *args, **kw)
      File "/Users/daniel/Workspace/buildout.tr-eshop/src/node.ext.ldap/src/node/ext/ldap/_node.py", line 193, in __init__
        self._ldap_session = LDAPSession(props)
      File "/Users/daniel/Workspace/buildout.tr-eshop/src/node.ext.ldap/src/node/ext/ldap/session.py", line 19, in __init__
        connector = LDAPConnector(props=props)
      File "/Users/daniel/Workspace/buildout.tr-eshop/src/node.ext.ldap/src/node/ext/ldap/base.py", line 112, in __init__
        self._ignore_cert = props.ignore_cert
    AttributeError: 'LDAPProps' object has no attribute 'ignore_cert'

**Comment by saily** [comment]
Sorry guy's - used local checkouts of both packages.
